version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=connector
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=connectordb

  keycloakdb:
    image: postgres:latest
    ports:
      - 15433:5432    
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_PRODUCTION: true  
      KC_HTTP_ENABLED: true
      KEYCLOAK_ENABLE_TLS: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}      
    command: "-v start --import-realm --https-key-store-file=/opt/keycloak/data/certs/keycloak.server.keystore.p12 --https-key-store-password=${TLS_KEYSTORE_PASSWORD}"
    depends_on:
      - keycloakdb
    ports:
      - ${KEYCLOAK_PORT}:8443
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keystore_tls.p12:/opt/keycloak/data/certs/keycloak.server.keystore.p12    
    extra_hosts:
      - "${CONNECTOR_FQDN}:host-gateway"        

  connector:
    image: ghcr.io/gate-institute/dataspace-connector:8.0.2-G4
    ports:
      - ${CONNECTOR_PORT}:8081
      - 8080:5005
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./config.json:/config/config.json
      - ./keystore.p12:/config/keystore.p12
      - ./truststore.p12:/config/truststore.p12
      - ./keystore_tls.p12:/config/keystore_tls.p12
      - ./log4j2.xml:/app/log4j2.xml
      - ./V8.0.2__releaseV8.0.2-fix.sql:/app/BOOT-INF/classes/db/migration/V8.0.2__releaseV8.0.2.sql
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - CONFIGURATION_FORCE_RELOAD=true

      - DAPS_URL=https://${IDS_FQDN}
      - DAPS_TOKEN_URL=https://${IDS_FQDN}/auth/token
      - DAPS_KEY_URL=https://${IDS_FQDN}/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - DAPS_ENABLE_LOG_JWT=true
      - DAPS_JWT_SIGNATURE_ALGORITHM=ECDSA256
      
      - CONFIGURATION_KEYSTOREPASSWORD=${KEYSTORE_PASSWORD}
      
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=${ADMIN_PASSWORD}
      - SPRING_SECURITY_APP_NAME=app
      - SPRING_SECURITY_APP_PASSWORD=${APP_PASSWORD}

      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY-STORE=file:///config/keystore_tls.p12
      - SERVER_SSL_KEY-STORE-PASSWORD=${TLS_KEYSTORE_PASSWORD}

      - _JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#      - _JAVA_OPTIONS=-Djavax.net.debug=all -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/connectordb
      - SPRING_DATASOURCE_USERNAME=connector
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASEPLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      - CAMEL_TRUSTSTORE_PATH=/config/truststore.p12
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINEVERSION=8.0.2
      - SPRING_FLYWAY_BASELINEONMIGRATE=true
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      
      - CLEARING_HOUSE_URL=https://gateds-infra.gate-ai.eu:9999
      - CLEARING_HOUSE_PATH_LOG=messages/log
      - CLEARING_HOUSE_PATH_PROCESS=process

      - PORTAINER_APPLICATION_SCHEME=http
      - PORTAINER_APPLICATION_HOST=portainer
      - PORTAINER_APPLICATION_PORT=9000
      - PORTAINER_APPLICATION_USERNAME=admin
      - PORTAINER_APPLICATION_PASSWORD=${PORTAINER_PASSWORD}
      - PORTAINER_APPLICATION_CONNECTOR_NETWORK=${CONTAINER_NETWORK}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_ROOT=https://${CONNECTOR_FQDN}:${KEYCLOAK_PORT}
      # - SPRING_JPA_SHOW-SQL=true
      # - SPRING_JPA.PROPERTIES.HIBERNATE.FORMAT_SQL=true      
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  gateconnect-backend:
    image: ghcr.io/gate-institute/gateconnect-backend:0.0.12
    ports:
      - ${CONNECTOR_UI_BACKEND_PORT}:8080
    restart: always
    volumes:
      - ./keystore_tls.p12:/config/keystore_tls.p12
    environment:
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY-STORE=file:///config/keystore_tls.p12
      - SERVER_SSL_KEY-STORE-PASSWORD=${TLS_KEYSTORE_PASSWORD}
      - FRONTEND_ORIGIN=https://${CONNECTOR_FQDN}:${CONNECTOR_UI_PORT}
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=${ADMIN_PASSWORD}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_ROOT=https://${CONNECTOR_FQDN}:${KEYCLOAK_PORT}
      - GATECONNECT_ID=https://${CONNECTOR_FQDN}:${CONNECTOR_PORT}
      - GATECONNECT_URL=https://${CONNECTOR_FQDN}:${CONNECTOR_PORT}
      - GATECONNECT_USERNAME=admin
      - GATECONNECT_PASSWORD=${ADMIN_PASSWORD}

  gateconnect-dashboard:
    image: ghcr.io/gate-institute/gateconnect-dashboard:0.0.27
    ports:
      - ${CONNECTOR_UI_PORT}:443
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./fullchain.pem:/etc/nginx/ssl/${CONNECTOR_FQDN}/fullchain.pem
      - ./privkey.pem:/etc/nginx/ssl/${CONNECTOR_FQDN}/privkey.pem
    environment:
      - CONNECTOR_FQDN=${CONNECTOR_FQDN}
      - BACKEND_ROOT=https://${CONNECTOR_FQDN}:${CONNECTOR_UI_BACKEND_PORT}
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    ports:
#      - 9443
      - ${PORTAINER_PORT}:9000
    restart: always
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      
      
volumes:
  pgdata:
  portainer-data:
  pgdata_keycloak:

